#The likelihood function
#follows the same definition as seen in Tian-Rui Xu, et. al, 
#Supplementary Materials for Inferring Signaling Pathway 
#Topologies from Multiple Perturbation Measurements of Specific 
#Biochemical Species

class LikelihoodFunction:
    """ This class defines a likelihood function for experimental data
        generated by system a system of ODEs.""" 

        
    def __init__ (self, ode, sigma):
        """ Default constructor. ode is the system that rules the 
            observed system. """
        self.__ode = ode
        self.__sigma = sigma
        
    
    def get_likelihood (self, X, var, t, theta):
        """ Given the observed X of values of variable var on time t, 
            what is the probability that X happened given that the 
            system paraters are theta. Initial variable values are
            stored in the ode object. """
        return 0

